# Generated by Django 5.2.11 on 2026-02-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the company', max_length=50, unique=True, verbose_name='Company Code')),
                ('name', models.CharField(help_text='Name of the company', max_length=255, verbose_name='Company Name')),
                ('legal_name', models.CharField(blank=True, help_text='Official legal name of the company', max_length=255, verbose_name='Legal Name')),
                ('company_type', models.CharField(choices=[('own', 'Own Company'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('both', 'Customer & Vendor')], default='customer', help_text='Type of company relationship', max_length=20, verbose_name='Company Type')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50, verbose_name='Tax ID/NPWP')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='Indonesia', max_length=100, verbose_name='Country')),
                ('currency', models.CharField(default='IDR', help_text='Default currency for transactions', max_length=10, verbose_name='Currency')),
                ('payment_terms', models.IntegerField(default=30, help_text='Default payment terms in days', verbose_name='Payment Terms (Days)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Credit limit for this company', max_digits=15, verbose_name='Credit Limit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company is currently active', verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='organizatio_code_dbdfe6_idx'), models.Index(fields=['name'], name='organizatio_name_190560_idx'), models.Index(fields=['company_type'], name='organizatio_company_be9ae0_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_0ffa49_idx')],
            },
        ),
    ]
