# Generated by Django 5.2.11 on 2026-02-13 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the warehouse', max_length=50, unique=True, verbose_name='Warehouse Code')),
                ('name', models.CharField(help_text='Name of the warehouse', max_length=255, verbose_name='Warehouse Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the warehouse', verbose_name='Description')),
                ('address_line1', models.CharField(blank=True, help_text='Street address', max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, help_text='Additional address information', max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text='State or province name', max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, default='Indonesia', help_text='Country name', max_length=100, verbose_name='Country')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this warehouse is currently active', verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default warehouse for the company', verbose_name='Default Warehouse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(help_text='Company that owns this warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='organizations.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['company', 'code'],
                'indexes': [models.Index(fields=['company', 'code'], name='organizatio_company_d84503_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_0c9811_idx')],
            },
        ),
    ]
