# Generated by Django 5.2.11 on 2026-02-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the item', max_length=50, unique=True, verbose_name='Item Code')),
                ('name', models.CharField(help_text='Name of the item', max_length=255, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item', verbose_name='Description')),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., pcs, kg, liter)', max_length=50, verbose_name='Unit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='master_item_code_6106d6_idx'), models.Index(fields=['name'], name='master_item_name_63fea0_idx'), models.Index(fields=['is_active'], name='master_item_is_acti_93c305_idx')],
            },
        ),
    ]
