# Generated by Django 5.2.11 on 2026-02-13 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the unit of measure', max_length=20, unique=True, verbose_name='UOM Code')),
                ('name', models.CharField(help_text='Name of the unit of measure', max_length=100, verbose_name='UOM Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the UOM', verbose_name='Description')),
                ('uom_type', models.CharField(choices=[('weight', 'Weight'), ('length', 'Length'), ('volume', 'Volume'), ('quantity', 'Quantity'), ('time', 'Time'), ('other', 'Other')], default='quantity', help_text='Type/category of the unit', max_length=50, verbose_name='UOM Type')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Conversion factor to base unit', max_digits=10, verbose_name='Conversion Factor')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this UOM is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('base_uom', models.ForeignKey(blank=True, help_text='Reference base unit for conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_uoms', to='master.uom', verbose_name='Base UOM')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='master_uom_code_d0132f_idx'), models.Index(fields=['name'], name='master_uom_name_8e6d26_idx'), models.Index(fields=['uom_type'], name='master_uom_uom_typ_e155b1_idx'), models.Index(fields=['is_active'], name='master_uom_is_acti_a69f23_idx')],
            },
        ),
    ]
