# Generated by Django 5.2.11 on 2026-02-13 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1.0, help_text='Conversion factor from base UOM', max_digits=10, verbose_name='Conversion Factor')),
                ('is_base_uom', models.BooleanField(default=False, help_text='Is this the base/default unit for this item', verbose_name='Is Base UOM')),
                ('is_purchase_uom', models.BooleanField(default=False, help_text='Can be used for purchasing', verbose_name='Is Purchase UOM')),
                ('is_sales_uom', models.BooleanField(default=False, help_text='Can be used for sales', verbose_name='Is Sales UOM')),
                ('is_stock_uom', models.BooleanField(default=False, help_text='Can be used for stock/inventory', verbose_name='Is Stock UOM')),
                ('barcode', models.CharField(blank=True, help_text='Barcode for this item-UOM combination', max_length=100, verbose_name='Barcode')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item-UOM is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_uoms', to='master.item', verbose_name='Item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_uoms', to='master.uom', verbose_name='Unit of Measure')),
            ],
            options={
                'verbose_name': 'Item UOM',
                'verbose_name_plural': 'Item UOMs',
                'ordering': ['item', 'uom'],
                'indexes': [models.Index(fields=['item', 'uom'], name='master_item_item_id_11caad_idx'), models.Index(fields=['item', 'is_base_uom'], name='master_item_item_id_947acd_idx'), models.Index(fields=['barcode'], name='master_item_barcode_3c0b7d_idx'), models.Index(fields=['is_active'], name='master_item_is_acti_f0891c_idx')],
                'unique_together': {('item', 'uom')},
            },
        ),
    ]
