# Generated by Django 5.2.11 on 2026-02-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_itemuom'),
        ('organizations', '0002_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the rack', max_length=50, unique=True, verbose_name='Rack Code')),
                ('name', models.CharField(help_text='Name of the rack', max_length=255, verbose_name='Rack Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the rack', verbose_name='Description')),
                ('zone', models.CharField(blank=True, help_text='Zone or area within the warehouse', max_length=50, verbose_name='Zone')),
                ('aisle', models.CharField(blank=True, help_text='Aisle number or identifier', max_length=50, verbose_name='Aisle')),
                ('bay', models.CharField(blank=True, help_text='Bay or section identifier', max_length=50, verbose_name='Bay/Section')),
                ('level', models.CharField(blank=True, help_text='Level or shelf number', max_length=50, verbose_name='Level')),
                ('capacity', models.DecimalField(decimal_places=2, default=0, help_text='Storage capacity (cubic meters or other unit)', max_digits=10, verbose_name='Capacity')),
                ('max_weight', models.DecimalField(decimal_places=2, default=0, help_text='Maximum weight capacity (kg)', max_digits=10, verbose_name='Max Weight')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rack is currently active', verbose_name='Active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the rack', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('warehouse', models.ForeignKey(help_text='Warehouse that contains this rack', on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='organizations.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['warehouse', 'code'],
                'indexes': [models.Index(fields=['warehouse', 'code'], name='master_rack_warehou_277b3f_idx'), models.Index(fields=['is_active'], name='master_rack_is_acti_956714_idx'), models.Index(fields=['zone', 'aisle'], name='master_rack_zone_680677_idx')],
            },
        ),
    ]
