# Generated by Django 5.2.11 on 2026-02-17 04:50

import django.db.models.deletion # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_rack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the role', max_length=100, unique=True, verbose_name='Role Name')),
                ('code', models.CharField(help_text='Unique code for the role', max_length=50, unique=True, verbose_name='Role Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the role', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'master_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the menu', max_length=100, verbose_name='Menu Name')),
                ('code', models.CharField(help_text='Unique code for the menu', max_length=50, unique=True, verbose_name='Menu Code')),
                ('icon', models.CharField(blank=True, help_text='Icon class or name for the menu', max_length=100, verbose_name='Icon')),
                ('url', models.CharField(blank=True, help_text='URL path for the menu', max_length=255, verbose_name='URL')),
                ('order', models.IntegerField(default=0, help_text='Display order of the menu', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu is active', verbose_name='Active')),
                ('module', models.CharField(blank=True, help_text='Module name (e.g., master, inventory, transaction)', max_length=100, verbose_name='Module')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master.menu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'master_menu',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='Module name (e.g., master, inventory, transaction)', max_length=100, verbose_name='Module')),
                ('feature', models.CharField(help_text='Feature name (e.g., item, uom, rack)', max_length=100, verbose_name='Feature')),
                ('permission', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import')], help_text='Permission type', max_length=20, verbose_name='Permission')),
                ('is_granted', models.BooleanField(default=True, help_text='Whether this permission is granted', verbose_name='Is Granted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.ForeignKey(help_text='Role that has this accessibility', on_delete=django.db.models.deletion.CASCADE, related_name='accessibilities', to='master.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Accessibility',
                'verbose_name_plural': 'Accessibilities',
                'db_table': 'master_accessibility',
                'ordering': ['role', 'module', 'feature', 'permission'],
                'unique_together': {('role', 'module', 'feature', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='RoleMenuAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True, help_text='Whether the role can access this menu', verbose_name='Can Access')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('menu', models.ForeignKey(help_text='Menu that can be accessed', on_delete=django.db.models.deletion.CASCADE, related_name='role_accesses', to='master.menu', verbose_name='Menu')),
                ('role', models.ForeignKey(help_text='Role that has access to the menu', on_delete=django.db.models.deletion.CASCADE, related_name='menu_accesses', to='master.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role Menu Access',
                'verbose_name_plural': 'Role Menu Accesses',
                'db_table': 'master_role_menu_access',
                'ordering': ['role', 'menu'],
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
